name: deploy-neon-prod

on:
    push:
        branches:
            - 'main'
        paths:
            - 'sql/script.sql'

permissions:
    pull-requests: write

jobs:    
    deploy-producao:
        name: Deploy no banco em produção
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Instala postgres
            run: |
                sudo apt-get update -y
                sudo apt-get install -y postgresql-client

          - name: Exclui banco atual
            env:
                DATABASE_URL: ${{ secrets.NEON_PROD_DATABASE_URL }}
            run: |
                psql "$DATABASE_URL" -v ON_ERROR_STOP=1 <<'SQL'
                    DROP SCHEMA IF EXISTS public CASCADE;
                    DROP SCHEMA IF EXISTS pdca CASCADE;
                    DROP SCHEMA IF EXISTS auditoria CASCADE;
                SQL

          - name: Aplica script.sql no banco de produção
            env:
                DATABASE_URL: ${{ secrets.NEON_PROD_DATABASE_URL }}
            run: |
                psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f  sql/script.sql

          - name: Configura python
            uses: actions/setup-python@v5
            with:
                python-version: '3.14'
            
          - name: Instala dependências Python
            run: pip install -r python/requirements.txt

          - name: Executa dataload
            env: 
                FULL_URL: ${{ secrets.NEON_PROD_DATABASE_URL }}
                PEPPER: ${{ secrets.PEPPER }}
            run: |
                papermill python/dataload.ipynb python/dataload_executado.ipynb
